name: CI/CD to VPS (Public Flask)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/flask-public-demo:latest,${{ secrets.DOCKERHUB_USER }}/flask-public-demo:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH known_hosts
        run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /flask-public
            docker compose pull
            docker compose up -d
            docker image prune -f

  health-check:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check (retry with backoff)
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://flask-public.bangraply.cloud/
          follow-redirect: true
          max-attempts: 6
          retry-delay: 10s
